[INFO][2024-10-17 16:09:41][config.py:301] - [INIT] load config: {'channel_type': 'wx', 'model': 'MyModel', 'zhipu_ai_api_key': '123*****123', 'zhipu_ai_api_base': 'http://127.0.0.1:6006/v1/chat/completions', 'text_to_image': '', 'voice_to_text': '', 'text_to_voice': '', 'proxy': '', 'hot_reload': False, 'single_chat_prefix': ['', 'bot', '@bot'], 'single_chat_reply_prefix': '[bot] ', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群', 'ChatGPT测试群2'], 'image_create_prefix': ['画'], 'speech_recognition': True, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 2500, 'expires_in_seconds': 3600, 'character_desc': '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'temperature': 0.7, 'subscribe_msg': '感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': False, 'linkai_api_key': '*****', 'linkai_app_code': ''}
[INFO][2024-10-17 16:09:41][config.py:227] - [Config] User datas file not found, ignore.
[ERROR][2024-10-17 16:09:42][app.py:79] - App startup failed!
[ERROR][2024-10-17 16:09:42][app.py:80] - No module named 'lib'
Traceback (most recent call last):
  File "D:\VSCodeWorkPlace\WechatRobot\WechatRobot\app.py", line 74, in run
    start_channel(channel_name)
  File "D:\VSCodeWorkPlace\WechatRobot\WechatRobot\app.py", line 30, in start_channel
    channel = channel_factory.create_channel(channel_name)
  File "D:\VSCodeWorkPlace\WechatRobot\WechatRobot\channel\channel_factory.py", line 16, in create_channel
    from channel.wechat.wechat_channel import WechatChannel
  File "D:\VSCodeWorkPlace\WechatRobot\WechatRobot\channel\wechat\wechat_channel.py", line 18, in <module>
    from channel.wechat.wechat_message import *
  File "D:\VSCodeWorkPlace\WechatRobot\WechatRobot\channel\wechat\wechat_message.py", line 7, in <module>
    from lib import itchat
ModuleNotFoundError: No module named 'lib'
[INFO][2024-10-17 16:10:03][config.py:301] - [INIT] load config: {'channel_type': 'wx', 'model': 'MyModel', 'zhipu_ai_api_key': '123*****123', 'zhipu_ai_api_base': 'http://127.0.0.1:6006/v1/chat/completions', 'text_to_image': '', 'voice_to_text': '', 'text_to_voice': '', 'proxy': '', 'hot_reload': False, 'single_chat_prefix': ['', 'bot', '@bot'], 'single_chat_reply_prefix': '[bot] ', 'group_chat_prefix': ['@bot'], 'group_name_white_list': ['ChatGPT测试群', 'ChatGPT测试群2'], 'image_create_prefix': ['画'], 'speech_recognition': True, 'group_speech_recognition': False, 'voice_reply_voice': False, 'conversation_max_tokens': 2500, 'expires_in_seconds': 3600, 'character_desc': '你是基于大语言模型的AI智能助手，旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。', 'temperature': 0.7, 'subscribe_msg': '感谢您的关注！\n这里是AI智能助手，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。', 'use_linkai': False, 'linkai_api_key': '*****', 'linkai_app_code': ''}
[INFO][2024-10-17 16:10:03][config.py:227] - [Config] User datas file not found, ignore.
[INFO][2024-10-17 16:10:03][plugin_manager.py:50] - Loading plugins config...
[INFO][2024-10-17 16:10:03][plugin_manager.py:88] - Scaning plugins ...
[INFO][2024-10-17 16:10:03][plugin_manager.py:41] - Plugin Banwords_v1.0 registered, path=./plugins\banwords
[INFO][2024-10-17 16:10:03][plugin_manager.py:41] - Plugin BDunit_v0.1 registered, path=./plugins\bdunit
[INFO][2024-10-17 16:10:03][plugin_manager.py:41] - Plugin Dungeon_v1.0 registered, path=./plugins\dungeon
[INFO][2024-10-17 16:10:03][plugin_manager.py:41] - Plugin Finish_v1.0 registered, path=./plugins\finish
[INFO][2024-10-17 16:10:03][plugin_manager.py:41] - Plugin Godcmd_v1.0 registered, path=./plugins\godcmd
[INFO][2024-10-17 16:10:03][plugin_manager.py:41] - Plugin Hello_v0.1 registered, path=./plugins\hello
[INFO][2024-10-17 16:10:03][plugin_manager.py:41] - Plugin Keyword_v0.1 registered, path=./plugins\keyword
[INFO][2024-10-17 16:10:03][plugin_manager.py:41] - Plugin linkai_v0.1.0 registered, path=./plugins\linkai
[INFO][2024-10-17 16:10:03][plugin_manager.py:41] - Plugin Role_v1.0 registered, path=./plugins\role
[WARNING][2024-10-17 16:10:03][plugin_manager.py:113] - Failed to import plugin tool: No module named 'chatgpt_tool_hub'
[ERROR][2024-10-17 16:10:03][plugin_manager.py:182] - Plugin tool not found, but found in plugins.json
[INFO][2024-10-17 16:10:03][godcmd.py:194] - [Godcmd] 因未设置口令，本次的临时口令为0678。
[INFO][2024-10-17 16:10:03][godcmd.py:210] - [Godcmd] inited
[INFO][2024-10-17 16:10:03][keyword.py:40] - [keyword] {}
[INFO][2024-10-17 16:10:03][keyword.py:42] - [keyword] inited.
[INFO][2024-10-17 16:10:03][linkai.py:35] - [LinkAI] inited, config={'group_app_map': {'测试群名1': 'default', '测试群名2': 'Kv2fXJcH'}, 'midjourney': {'enabled': False, 'auto_translate': True, 'img_proxy': True, 'max_tasks': 3, 'max_tasks_per_user': 1, 'use_image_create_prefix': True}, 'summary': {'enabled': False, 'group_enabled': True, 'max_file_size': 5000, 'type': ['FILE', 'SHARING']}}
[INFO][2024-10-17 16:10:03][role.py:69] - [Role] inited
[INFO][2024-10-17 16:10:03][dungeon.py:56] - [Dungeon] inited
[INFO][2024-10-17 16:10:03][hello.py:38] - [Hello] inited
[INFO][2024-10-17 16:10:03][finish.py:23] - [Finish] inited
[INFO][2024-10-17 16:10:30][app.py:20] - signal 2 received, exiting...
[INFO][2024-10-17 16:10:30][config.py:236] - [Config] User datas saved.
